server:
  port: 8010
info:
  app:
    name: @project.artifactId@


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: microservice-consumer-movie